package com.osdepym.exception;

public class ErrorMessages {	
	// Newsletter
	public static final String NEWSLETTER_DUPLICATE_ERROR = "El email ya se encuentra registrado.";
	
	public static final String UNKNOWN_ERROR = "Se ha producido un error inesperado, intentelo de nuevo mas tarde.";
	public static final String DATABASE_GET_ERROR = "Error al intentar obtener registro, intentelo de nuevo mas tarde.";	
	public static final String DATABASE_SAVE_ERROR = "Error al intentar guardar registro, intentelo de nuevo mas tarde.";	
	public static final String DATABASE_DELETE_ERROR = "Error al intentar borrar registro, intentelo de nuevo mas tarde.";	
	public static final String LOAD_CONTACT_ERROR = "Se ha producido un error al cargar el formulario, intentelo de nuevo mas tarde.";	
	public static final String PROCESS_CONTACT_ERROR = "Se ha producido un error al procesar el formulario, intentelo de nuevo mas tarde.";
}
